export const PINYIN_DATA = {
    initials: [
        { char: 'b', emoji: '🍍', word: '菠萝 (bō luó)', pronounce: '玻' },
        { char: 'p', emoji: '🍇', word: '葡萄 (pú táo)', pronounce: '坡' },
        { char: 'm', emoji: '🎩', word: '帽子 (mào zi)', pronounce: '摸' },
        { char: 'f', emoji: '✈️', word: '飞机 (fēi jī)', pronounce: '佛' },
        { char: 'd', emoji: '🥚', word: '鸡蛋 (jī dàn)', pronounce: '得' },
        { char: 't', emoji: '🐰', word: '兔子 (tù zi)', pronounce: '特' },
        { char: 'n', emoji: '🎃', word: '南瓜 (nán guā)', pronounce: '讷' },
        { char: 'l', emoji: '🐒', word: '猴子 (hóu zi)', pronounce: '勒' },
        { char: 'g', emoji: '🐦', word: '鸽子 (gē zi)', pronounce: '哥' },
        { char: 'k', emoji: '蝌', word: '蝌蚪 (kē dǒu)', pronounce: '科' },
        { char: 'h', emoji: '🐯', word: '老虎 (lǎo hǔ)', pronounce: '喝' },
        { char: 'j', emoji: '🐔', word: '母鸡 (mǔ jī)', pronounce: '鸡' },
        { char: 'q', emoji: '🎈', word: '气球 (qì qiú)', pronounce: '七' },
        { char: 'x', emoji: '🍉', word: '西瓜 (xī guā)', pronounce: '西' },
        { char: 'zh', emoji: '🕷️', word: '蜘蛛 (zhī zhū)', pronounce: '知' },
        { char: 'ch', emoji: '🥄', word: '吃饭 (chī fàn)', pronounce: '吃' },
        { char: 'sh', emoji: '🦁', word: '狮子 (shī zi)', pronounce: '狮' },
        { char: 'r', emoji: '🌞', word: '日出 (rì chū)', pronounce: '日' },
        { char: 'z', emoji: '✍️', word: '写字 (xiě zì)', pronounce: '资' },
        { char: 'c', emoji: '🦔', word: '刺猬 (cì wei)', pronounce: '刺' },
        { char: 's', emoji: '🐛', word: '蚕丝 (cán sī)', pronounce: '丝' },
        { char: 'y', emoji: '👕', word: '衣服 (yī fu)', pronounce: '医' },
        { char: 'w', emoji: '🏠', word: '房屋 (fáng wū)', pronounce: '屋' }
    ],
    finals: [
        { char: 'a', emoji: '😮', word: '啊 (a)', pronounce: '啊' },
        { char: 'o', emoji: '🐓', word: '喔 (o)', pronounce: '喔' },
        { char: 'e', emoji: '🦢', word: '鹅 (é)', pronounce: '鹅' },
        { char: 'i', emoji: '👕', word: '衣 (yī)', pronounce: '衣' },
        { char: 'u', emoji: '🏠', word: '屋 (wū)', pronounce: '乌' },
        { char: 'ü', emoji: '🐟', word: '鱼 (yú)', pronounce: '迂' },
        { char: 'ai', emoji: '👵', word: '爱 (ài)', pronounce: '爱' },
        { char: 'ei', emoji: '🥤', word: '杯 (bēi)', pronounce: '杯' },
        { char: 'ui', emoji: '🐢', word: '龟 (guī)', pronounce: '威' },
        { char: 'ao', emoji: '🧥', word: '袄 (ǎo)', pronounce: '袄' },
        { char: 'ou', emoji: '🐦', word: '海鸥 (hǎi ōu)', pronounce: '欧' },
        { char: 'iu', emoji: '柳', word: '柳树 (liǔ shù)', pronounce: '优' },
        { char: 'ie', emoji: '🥥', word: '椰子 (yē zi)', pronounce: '耶' },
        { char: 'üe', emoji: '🌙', word: '月亮 (yuè liang)', pronounce: '约' },
        { char: 'er', emoji: '👂', word: '耳朵 (ěr duo)', pronounce: '二' },
        { char: 'an', emoji: '🚪', word: '天安门 (tiān ān mén)', pronounce: '安' },
        { char: 'en', emoji: '摁', word: '摁门铃 (èn)', pronounce: '恩' },
        { char: 'in', emoji: '🎵', word: '音乐 (yīn yuè)', pronounce: '音' },
        { char: 'un', emoji: '☁️', word: '云 (yún)', pronounce: '温' },
        { char: 'ün', emoji: '☁️', word: '云 (yún)', pronounce: '晕' },
        { char: 'ang', emoji: '🐏', word: '山羊 (shān yáng)', pronounce: '昂' },
        { char: 'eng', emoji: '💡', word: '台灯 (tái dēng)', pronounce: '恩' }, // Hard to find exact char for eng alone, '亨' (heng) is close enough for sound
        { char: 'ing', emoji: '🦅', word: '老鹰 (lǎo yīng)', pronounce: '英' },
        { char: 'ong', emoji: '🕰️', word: '闹钟 (nào zhōng)', pronounce: '翁' } // ong -> hong
    ],
    overall: [
        { char: 'zhi', emoji: '🧶', word: '织毛衣 (zhī)', pronounce: '织' },
        { char: 'chi', emoji: '🥄', word: '吃饭 (chī)', pronounce: '吃' },
        { char: 'shi', emoji: '🦁', word: '狮子 (shī)', pronounce: '狮' },
        { char: 'ri', emoji: '🌞', word: '日 (rì)', pronounce: '日' },
        { char: 'zi', emoji: '🟣', word: '紫色 (zǐ)', pronounce: '紫' },
        { char: 'ci', emoji: '🦔', word: '刺猬 (cì)', pronounce: '刺' },
        { char: 'si', emoji: '🧵', word: '丝瓜 (sī)', pronounce: '丝' },
        { char: 'yi', emoji: '👕', word: '衣服 (yī)', pronounce: '衣' },
        { char: 'wu', emoji: '🏠', word: '房屋 (wū)', pronounce: '屋' },
        { char: 'yu', emoji: '🐟', word: '鱼 (yú)', pronounce: '鱼' },
        { char: 'ye', emoji: '🥥', word: '椰子 (yē)', pronounce: '耶' },
        { char: 'yue', emoji: '🌙', word: '月亮 (yuè)', pronounce: '月' },
        { char: 'yuan', emoji: '⭕', word: '圆圈 (yuán)', pronounce: '圆' },
        { char: 'yin', emoji: '🎵', word: '音乐 (yīn)', pronounce: '音' },
        { char: 'yun', emoji: '☁️', word: '云 (yún)', pronounce: '云' },
        { char: 'ying', emoji: '🦅', word: '老鹰 (yīng)', pronounce: '鹰' }
    ]
};
